# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: Enrique Perez Cozar <br>
Url: https://github.com/enriquetracker/03MIAR---Algoritmos-de-Optimizacion-2022<br>
Problema:
> 1. Sesiones de doblaje <br>


Descripción del problema:(copiar enunciado)

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graben. No es posible grabar más de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los servicios de los actores de doblaje sea el menor posible. Los datos son:

Número de actores: 10

Número de tomas : 30

Actores/Tomas : https://bit.ly/36D8IuK

- 1 indica que el actor participa en la toma
- 0 en caso contrario

---


                               

### (*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?

---

Si no tenemos encuenta ninguna restricción, para el conjunto de datos de entrada con 30 tomas y 10 actores, el numero de soluciones posibles es el factorial de 30 (30!).

Aunque habría 30! soluciones posibles, el gasto de los servicios seria el mismo para todas las soluciones, ya que todas las tomas se rodarían en el mismo dia y habría que pagar por cada actor que asistiera al rodaje una única vez, teniendo en cuenta que las tomas se rodarían de una en una.


### ¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.

---

Si tenemos en cuenta la restricciones, este numero se reduce ligeramente, ya que cada dia se graban máximo seis tomas. Este calculo es el siguiente:


$$SolucionesPosibles = \frac{30!}{6!24!} * \frac{24!}{6!19!} *\frac{18!}{6!12!} *\frac{12!}{6!6!} = \frac{30!}{6!*6!*6!*6!*6!}








### Modelo para el espacio de soluciones<br>
### (*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)


Respuesta

---

En un primer momento, para el algoritmo de fuerza bruta, se ha utilizado un array de numpy para almacenar los datos de las 30 tomas y todas las posibles combinaciones en paquetes de 6.

La solución se da en una lista que contiene los datos de las tomas en grupos de 6 y el coste asociado a esa agrupación.

En el algoritmo de recocido simulado, se ha aligerado la solución, almacenando en una lista unicamente el orden en el que se rodará cada toma para luego evaluarla en la función de coste.

En cuanto a estas estructuras son simples y debido a la naturaleza del problema, unicamente conviene utilizar la mas eficiente para reducir el tiempo de procesado.


### Según el modelo para el espacio de soluciones<br>
### (*)¿Cual es la función objetivo?

### (*)¿Es un problema de maximización o minimización?

Respuesta

---

La función objetivo en este problema determina el costo total de los actores para grabar todas las tomas. Así, teniendo en cuenta, que el actor cobra por sesión de grabación y que cada dia se pueden grabar un máximo de 6 sesiones, la función objetivo queda de la siguiente forma:

\begin{equation}
\displaystyle Y = C\cdot  \sum_{i=0}^{n=\frac{N}{6}} x_i
\end{equation}

Donde **Y** es el coste total, **N** el número de tomas , **<b>x<sub>i</sub></b>** el número de actores que participa en la sesión y **C** el coste diario por actor.

Es un problema de **minimización** ya que hay que buscar que el coste sea mínimo y por tanto que los actores que participan en cada sesión sean los menos posibles.



### Diseña un algoritmo para resolver el problema por fuerza bruta

Respuesta

---

Un algoritmo de fuerza bruta se caracteriza por buscar la solución optima a través de recorrer todo el espacio de soluciones, debido a las cantidad de posibles soluciones descritas anteriormente, la ejecución de este algoritmo requerirá de un tiempo desorbitado, por lo tanto, se planteará pero no se ejecutará.

Adicionalmente, para hacerlo algo mas libiano, se ha introducido una condición para descartar las soluciones en el momento en el que se haya superado la solución óptima previa, esto hará que el algoritmo no termine de recorrer alguno de los caminos del espacio de soluciones.

En el siguiente diagrama de proceso se detalla como funciona el algoritmo desarrollado en las siguientes celdas.

<div style="display: flex; justify-content: center;">
<img src="esquema.png" alt="Texto alternativo">
</div>

Para el desarrollo del algoritmo de ha hecho uso de la recursividad para ir recorriendo el espacio de soluciones.


In [6]:
import numpy as np
import itertools

#Carga de datos
CSVData = open("data.csv")
datos = np.loadtxt(CSVData, delimiter=",", dtype=np.int8)

In [7]:
#Funcion para obtener las combinaciones de un conjunto de entrada en k grupos
def list_combs(iterable, k): 
    return np.array(list(itertools.combinations(iterable, k)))

In [8]:
#Funcion para eliminar datos de un conjunto 
def eliminar_filas(datos,pack):
    filas_eliminar = []
    for i in range(len(datos)):
        for j in range(len(pack)):
            if np.array_equal(datos[i], pack[j]):
                filas_eliminar.append(i)
                pack = np.delete(pack, j, axis=0)
                break

    return np.delete(datos, filas_eliminar, axis=0)

In [9]:
#Funcion recursiva para recorrer el espacio de soluciones y obtener la solución optima.
def agrupar_en_packs_6(data,lstSol,coste):
    
    global minimoactual
    global listaPack
    
    packages = list_combs(data, 6)

    for pack in packages:
        lstSolAux = lstSol.copy()
        if len(data)==30:
            coste=0

        data2 = eliminar_filas(data,pack)
        
        if len(data2) == 0:
            coste = coste + np.count_nonzero(sum(pack))
            print(coste)
            lstSol.append(pack)
            if coste<minimoactual:
                
                minimoactual = coste
                listaPack = lstSol
            continue
            

        coste = coste + np.count_nonzero(sum(pack))
        lstSolAux.append(pack)
        if(coste>minimoactual):
            continue
        agrupar_en_packs_6(data2,lstSolAux,coste)

In [10]:
# Se llama a la función y se pinta tanto el coste obtenido como la solución que produce ese minimo.
minimoactual = 10000
listaPack = []

agrupar_en_packs_6(datos,lstSol=[],coste=0)

print(minimoactual,listaPack)

KeyboardInterrupt: 

No se ha ejecutado hasta el final ya que el tiempo de ejecución era inasumible.

### Calcula la complejidad del algoritmo por fuerza bruta

Respuesta

---

La complejidad del algoritmo es del orden factorial, ya que iterará a través de todas las permutaciones de los elementos de entrada. Por tanto será:

\begin{equation}
\displaystyle O(\frac{N!}{\prod_{0}^{\frac{N}{d}} d!})
\end{equation}

Donde **N** es el número de tomas y **d** el número de sesiones por dia.

### (*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Respuesta

---

Para mejorar la complejidad del algoritmo de fuerza bruta se va a desarrollar un algoritmo de busqueda metaheurística como es el algoritmo de recocido simulado. Este algoritmo puede quedar atrapado en un mínimo local, por lo que no nos garantiza una solución optima, no obstante podemos ejecutar varias instancias del algoritmo para evaluar los resultados o encadenar ejecuciones.

El pseudocodigo del algoritmo de recocido simulado es el siguiente:

<div style="display: flex; justify-content: center;">
<img src="Pseudocode.png" alt="Texto alternativo">
</div>

Este pseudocódigo es genérico independientemente del problema, por lo que, la implementación del algoritmo de recocido simulado es bastante simple.

Para cualquier problema habrá que determinar una forma de encontrar una solución inicial, en este caso, la hemos generado aleatoriamente, y una forma de generar un vecino aleatorio, en este caso hemos utilizado la tecnica de subinversión de 2 opciones, que consiste en seleccionar aleatoriamente un punto de inicio y un punto de fin del array de soluciones he invertirlo para generar una nueva.

Hemos implementado la función de coste para evaluar las posibles soluciones y la temperatura de inicio (T0) la hemos determinado como un porcentaje del coste de la solución inicial, ya que debe estar en las mismas unidades que el coste.

Finalmente la temperatura la hemos actualizado exponencialmente.

In [11]:
import numpy as np
import random
import math


#Carga de datos
CSVData = open("data.csv")
datos = np.loadtxt(CSVData, delimiter=",", dtype=np.int8)

In [12]:
##Generador de la solución inicial.
def Generar_Solucion_Inicial(longitud):
    opciones = np.arange(0,longitud,1)
    lstSol=[]
    opcionesDel = opciones.copy()
    for x in range(len(opciones)):

        aleatorio = random.choice(opcionesDel)
        lstSol.append(aleatorio)
        opcionesDel = np.delete(opcionesDel,np.argmax(opcionesDel==aleatorio))

    return lstSol

In [13]:
##Generador del vecino aleatorio
def Generar_Vecino_Aleatorio(Sol):
    sol2=Sol.copy()
    num = random.randint(1,len(sol2)-2)
    num2 = random.randint(num+1,len(sol2))
    vector2 = Sol[num2:num-1:-1]
    sol2[num:num2+1]=vector2
    return sol2

In [14]:
#~#Funcion de costes

def eval_coste(sol,conjunto):
    cost=0

    for x in range((int)(len(sol)/6)):
        
        cost = cost + np.count_nonzero(sum([conjunto[sol[0+6*x]],conjunto[sol[1+6*x]],conjunto[sol[2+6*x]],conjunto[sol[3+6*x]],conjunto[sol[4+6*x]],conjunto[sol[5+6*x]]]))
    
        if len(sol)%6!=0:
            extra = len(sol)%6
            lstext=[]
            for y in range(extra):
                lstext.append(conjunto[sol[y-1]])
            cost = cost + np.count_nonzero(sum(lstext))
    return cost  

In [15]:
##Recocido Simulado
def recocido_simulado(alpha,L,Tf,sol_ini,conjuntoDatos):

    S_act = sol_ini.copy()
    
    T = 0.4*eval_coste(S_act,conjuntoDatos)

    while T>=Tf:

        for x in range(0,L):
            
            S_cand = Generar_Vecino_Aleatorio(S_act)

            delta = eval_coste(S_cand,conjuntoDatos)-eval_coste(S_act,conjuntoDatos)

            if(random.random()<math.exp(-delta/T) or delta<0):
                
                S_act = S_cand.copy()
                
        T=alpha*T
    
    return S_act

In [35]:
def pintar_sol(solucion,data):
    
    print(f"El coste mínimo seria de {eval_coste(solucion,data)} y el orden de las tomas seria: ")

    for x in range(5):
        print(f"Dia {x+1}: {solucion[0+6*x:6+6*x]}")

In [36]:
%%time

prim = Generar_Solucion_Inicial(30)

Solucion1 = recocido_simulado(0.90,1000,0.01,prim,datos)

pintar_sol(Solucion1,datos)


El coste mínimo seria de 27 y el orden de las tomas seria: 
Dia 1: [9, 25, 28, 7, 10, 20]
Dia 2: [26, 5, 3, 14, 2, 4]
Dia 3: [22, 18, 23, 13, 17, 16]
Dia 4: [6, 12, 24, 27, 8, 15]
Dia 5: [11, 21, 29, 0, 19, 1]
CPU times: total: 10.1 s
Wall time: 12.3 s


Con una temperatura final relativamente baja de 0.01, un coeficiente de cambio de temperatura de 0.9 y 1000 iteraciones por etapa de temperatura, se consiguen soluciones con un coste de entre 27 y 29 en unos 12 segundos.

Sin embargo siendo menos restrictivos se pueden obtener soluciones muy razonables en un tiempo mínimo. Como en el siguiente ejemplo:

In [37]:
%%time

prim = Generar_Solucion_Inicial(30)

Solucion2 = recocido_simulado(0.60,700,0.1,prim,datos)

pintar_sol(Solucion2,datos)


El coste mínimo seria de 30 y el orden de las tomas seria: 
Dia 1: [19, 21, 5, 28, 8, 0]
Dia 2: [12, 1, 22, 10, 4, 6]
Dia 3: [17, 13, 20, 16, 23, 18]
Dia 4: [24, 9, 15, 11, 7, 25]
Dia 5: [26, 2, 3, 27, 29, 14]
CPU times: total: 1.03 s
Wall time: 1.5 s


En este caso en mucho menos tiempo se obtienen soluciones de entre 27 y 33 de coste, esto permite obtener soluciones aceptables rápidamente permitiendo escalar a aplicaciones donde el tiempo es importante.

El algoritmo del recocido simulado permite la ejecución secuencial del algoritmo partiendo de la solución incial calculada en la etapa anterior, como se muestra en el siguiente ejemplo, lo que permite mejorar la primera solución obtenida.

In [39]:
%%time

prim = Generar_Solucion_Inicial(30)

Solucion3 = recocido_simulado(0.60,700,0.1,prim,datos)
Solucion4 = recocido_simulado(0.60,700,0.1,Solucion3,datos)

pintar_sol(Solucion3,datos)
pintar_sol(Solucion4,datos)

El coste mínimo seria de 30 y el orden de las tomas seria: 
Dia 1: [6, 22, 8, 1, 0, 19]
Dia 2: [3, 20, 2, 4, 14, 28]
Dia 3: [13, 7, 18, 27, 17, 11]
Dia 4: [25, 10, 23, 21, 9, 16]
Dia 5: [5, 24, 12, 15, 29, 26]
El coste mínimo seria de 27 y el orden de las tomas seria: 
Dia 1: [6, 12, 8, 27, 26, 5]
Dia 2: [10, 25, 9, 4, 11, 19]
Dia 3: [15, 21, 24, 1, 0, 29]
Dia 4: [17, 23, 13, 22, 18, 16]
Dia 5: [14, 7, 20, 3, 28, 2]
CPU times: total: 1.5 s
Wall time: 1.8 s


### (*)Calcula la complejidad del algoritmo

Respuesta

---

La complejidad del algoritmo de recocido simulado sería aproximadamente O(L * N), donde L es el número de iteraciónes en un estado de temperatura y N es el número de iteraciones del bucle principal, que está determinado por 
la temperatura inicial T, la temperatura final Tf y el factor de enfriamiento alpha.

### Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios


Respuesta

---

Para testear la robustez del algoritmo, vamos a generar dos nuevos conjuntos de datos, un primero con un mayor numero de datos y un segundo con la misma cantidad de datos y la solución óptima conocida.

**Conjunto 1: data_1**

Este conjunto contiene cuatro tomas adicionales, nuestro algoritmo esta diseñado de forma que agrupa en paquetes de 6 , el máximo de tomas que se permiten diariamente, al tener ahora un conjunto de datos cuya longitud no es múltiplo de 6 puede que no alcance la solución óptima.

**Conjunto 2: data_2**

Este conjunto va a tener un coste de 10 y vamos a ver si el algoritmo es capaz de alcanzar esta solución.

### Aplica el algoritmo al juego de datos generado


Respuesta

---

**Conjunto 1: data_1**

In [40]:
#Carga de datos
CSVData = open("data_1.csv")
datos_1 = np.loadtxt(CSVData, delimiter=",", dtype=np.int8)
print(datos_1)

[[1 1 1 1 1 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0]
 [0 1 0 0 1 0 1 0 0 0]
 [1 1 0 0 0 0 1 1 0 0]
 [0 1 0 1 0 0 0 1 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 1 0]
 [1 1 1 0 1 0 0 1 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0]
 [1 0 1 0 0 1 0 0 0 0]
 [1 1 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 1]
 [1 0 1 0 1 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 1]
 [1 0 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 1]
 [1 1 1 1 0 0 0 0 1 1]]


In [42]:
%%time

prim2 = Generar_Solucion_Inicial(len(datos_1))

Solucion5 = recocido_simulado(0.95,1300,0.01,prim2,datos_1)

pintar_sol(Solucion5,datos_1)

El coste mínimo seria de 41 y el orden de las tomas seria: 
Dia 1: [12, 27, 26, 5, 8, 6]
Dia 2: [14, 2, 28, 20, 7, 3]
Dia 3: [30, 24, 32, 15, 11, 21]
Dia 4: [13, 18, 16, 23, 22, 17]
Dia 5: [25, 19, 4, 1, 31, 10]
CPU times: total: 48.1 s
Wall time: 55.6 s


In [53]:
%%time

prim2 = Generar_Solucion_Inicial(len(datos_1))

Solucion6 = recocido_simulado(0.90,1000,0.01,prim2,datos_1)

pintar_sol(Solucion6,datos_1)

El coste mínimo seria de 46 y el orden de las tomas seria: 
Dia 1: [6, 26, 12, 1, 21, 19]
Dia 2: [3, 14, 20, 2, 28, 7]
Dia 3: [9, 11, 32, 31, 33, 30]
Dia 4: [13, 16, 22, 18, 23, 17]
Dia 5: [27, 8, 29, 15, 4, 24]
CPU times: total: 16 s
Wall time: 19.6 s


In [54]:
%%time

prim2 = Generar_Solucion_Inicial(len(datos_1))

Solucion7 = recocido_simulado(0.40,700,0.1,prim2,datos_1)

pintar_sol(Solucion7,datos_1)

El coste mínimo seria de 51 y el orden de las tomas seria: 
Dia 1: [14, 18, 16, 1, 2, 13]
Dia 2: [0, 25, 31, 33, 15, 19]
Dia 3: [26, 8, 29, 6, 5, 12]
Dia 4: [11, 23, 27, 32, 30, 24]
Dia 5: [20, 4, 28, 17, 21, 7]
CPU times: total: 969 ms
Wall time: 1.25 s


Vemos como en este caso entre emplear unos parametros iniciales mas restrictivos o menos restrictivos hay bastante diferencia, debido tanto al aumento en la longitud del conjunto como a la variación de forma. La dificultad para obtener soluciones aumenta y con ello el tiempo de procesamiento, al aumentar el espacio de soluciones, es mas probable que caigamos en un minimo local y nos alejemos de la solución óptima.

**Conjunto 2: data_2**

In [46]:
#Carga de datos
CSVData = open("data_2.csv")
datos_2 = np.loadtxt(CSVData, delimiter=",", dtype=np.int8)
print(datos_2)

[[1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]]


In [55]:
%%time

prim2 = Generar_Solucion_Inicial(len(datos_2))

Solucion8 = recocido_simulado(0.95,1300,0.005,prim2,datos_2)

pintar_sol(Solucion8,datos_2)

El coste mínimo seria de 10 y el orden de las tomas seria: 
Dia 1: [18, 21, 22, 23, 20, 19]
Dia 2: [11, 7, 6, 10, 8, 9]
Dia 3: [27, 29, 24, 25, 26, 28]
Dia 4: [14, 17, 15, 16, 12, 13]
Dia 5: [2, 1, 4, 5, 3, 0]
CPU times: total: 25.7 s
Wall time: 29.4 s


In [59]:
%%time

prim2 = Generar_Solucion_Inicial(len(datos_2))

Solucion9 = recocido_simulado(0.90,1000,0.01,prim2,datos_2)

pintar_sol(Solucion9,datos_2)

El coste mínimo seria de 12 y el orden de las tomas seria: 
Dia 1: [9, 8, 10, 11, 7, 6]
Dia 2: [23, 21, 20, 19, 22, 18]
Dia 3: [4, 14, 13, 12, 5, 17]
Dia 4: [29, 27, 24, 26, 25, 28]
Dia 5: [15, 0, 3, 1, 2, 16]
CPU times: total: 9.09 s
Wall time: 10.6 s


In [57]:
%%time

prim2 = Generar_Solucion_Inicial(len(datos_2))

Solucion10 = recocido_simulado(0.4,700,0.1,prim2,datos_2)

pintar_sol(Solucion10,datos_2)

El coste mínimo seria de 22 y el orden de las tomas seria: 
Dia 1: [13, 2, 17, 4, 12, 0]
Dia 2: [16, 9, 15, 11, 6, 8]
Dia 3: [1, 22, 5, 21, 23, 19]
Dia 4: [29, 25, 10, 3, 28, 7]
Dia 5: [18, 26, 20, 14, 24, 27]
CPU times: total: 641 ms
Wall time: 777 ms


En este caso, vemos como únicamente el primero ha llegado a la solución óptima y conforme los parametros se vuelven menos restrictivos, las soluciones encontradas son peores.

### Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Respuesta

---

https://www.youtube.com/playlist?list=PLlSRRJbf1_seR7BeZLqG-ln3K8D6Oo5ef

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Respuesta

---

Se podría avanzar en el algoritmo de forma que la restricción de tomas por dia, fuera un parametro configurable. Es algo sencillo y que lo haría mucho mas versátil.